# Generated by Django 6.0.2 on 2026-03-17 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0002_sample_rename_user_comment_username_user_is_online_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cost_range',
        ),
        migrations.CreateModel(
            name='ServiceBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposite', models.CharField(max_length=10)),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('balance', models.CharField(max_length=15)),
                ('custome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_com.service')),
            ],
        ),
    ]
