# Generated by Django 6.0.2 on 2026-02-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0002_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
