# Generated by Django 6.0.2 on 2026-03-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0003_remove_service_cost_range_servicebought'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost_range',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
