# Generated by Django 6.0.2 on 2026-02-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0003_remove_comment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
