# Generated by Django 6.0.2 on 2026-03-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0004_service_cost_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='minimum_deposite',
            field=models.CharField(default=40, max_length=5),
        ),
    ]
