# Generated by Django 6.0.2 on 2026-02-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='blank_profile.jpg', upload_to=''),
        ),
    ]
