# Generated by Django 6.0.2 on 2026-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0006_alter_user_bio_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_pic', models.ImageField(blank=True, default='blank.jpeg', null=True, upload_to='')),
                ('sample_name', models.CharField(max_length=50)),
                ('price_on_offer', models.CharField(max_length=20)),
                ('customer_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
