# Generated by Django 6.0.2 on 2026-03-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0006_cart_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebought',
            old_name='custome',
            new_name='customer',
        ),
    ]
