# Generated by Django 6.0.2 on 2026-03-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0007_rename_custome_servicebought_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebought',
            old_name='deposite',
            new_name='deposit',
        ),
    ]
