# Generated by Django 6.0.2 on 2026-03-19 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0009_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
