# Generated by Django 6.0.2 on 2026-03-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='item',
        ),
    ]
