# Generated by Django 6.0.2 on 2026-03-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0010_rename_product_cart_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
