# Generated by Django 6.0.2 on 2026-04-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0010_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='thumbnail',
            field=models.ImageField(blank=True, default='blank.jpeg', upload_to=''),
        ),
    ]
