# Generated by Django 6.0.2 on 2026-03-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0013_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('HD', 'Head'), ('CD', 'Creative Designer'), ('WK', 'Worker')], default='WK', max_length=2),
        ),
    ]
