# Generated by Django 6.0.2 on 2026-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0014_worker_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='service',
        ),
        migrations.AddField(
            model_name='worker',
            name='service',
            field=models.ManyToManyField(to='e_com.service'),
        ),
    ]
