# Generated by Django 6.0.2 on 2026-03-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0015_remove_worker_service_worker_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional_info',
            field=models.CharField(blank=True, default='Your imagination, our plan.', max_length=255),
        ),
    ]
