# Generated by Django 6.0.2 on 2026-03-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0016_alter_service_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=models.CharField(blank=True, default='1234578991', max_length=10),
        ),
    ]
