# Generated by Django 6.0.2 on 2026-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_com', '0017_user_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
