# Generated by Django 6.0.2 on 2026-03-12 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_messagereceived_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereceived',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message_app.messagesent'),
        ),
    ]
