# Generated by Django 6.0.2 on 2026-03-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0003_alter_messagereceived_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=500)),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
