# Generated by Django 6.0.2 on 2026-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0004_chathistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
