# Generated by Django 6.0.2 on 2026-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0005_alter_chathistory_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
